project:
  type: website
  output-dir: docs
  

website:
  title: "QTM 350 Data Science Computing"
  sidebar:
    background: primary
    logo: "images/course_image_2.png"
    pinned: true
    align: center
    # tools:
    #   - icon: github
    #     href: https://github.com/davi-moreira/2024S_dsc_emory_qtm_350
    #     text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      #- href: problemset.qmd
      #  text: Problem Sets
      # - href: finalproject.qmd
      #  text: Final Project
      - section: "Materials"
        contents: 
          - href: topics/topic-01.qmd
            text: "Topic 1: Intro"
          - href: topics/topic-02.qmd
            text: "Topic 2: Version Control"
          - href: topics/topic-03.qmd
            text: "Topic 3: Python"
          - href: topics/topic-04.qmd
            text: "Topic 4: Web Scraping"
          - href: topics/topic-05.qmd
            text: "Topic 5: Data Structures"
          - href: topics/topic-06.qmd
            text: "Topic 6: SQL"
          - href: topics/topic-07.qmd
            text: "Topic 7: NoSQL"
          - href: topics/topic-08.qmd
            text: "Topic 8: DSM"
          - href: topics/topic-09.qmd
            text: "Topic 9: CPM"
          - href: topics/topic-10.qmd
            text: "Topic 10: Cloud DB"
          - href: topics/topic-11.qmd
            text: "Topic 11: Final Project"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

